### ISSUE TITLE
Add endpoint to filter colleges by city and state.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#107]
### Description

**Notes**
+ The data of all the *colleges* is stored in the `data` folder. 
+ Use that data to filter colleges by city and state.
+ Define two endpoints `colleges/city={city_name}` to filter colleges by city and `/colleges/state={states_name}` to filter colleges by state.
+ User must be able to pass multiple cities and states.

**Comment by jpphilips** [comment]
Please asign to me

**Comment by himanshu007-creator** [comment]
Hey @nikhil25803 , as @jpphilips  has shown interest in contributing to #108 and #109  as well, so i would like to take up this issue if you dont mind.

**Comment by nikhil25803** [comment]
Hey @jpphilips , you already have been assigned one issue. So assigning this one to @himanshu007-creator.

**Comment by nikhil25803** [comment]
Hey @himanshu007-creator, any updates?
