### ISSUE TITLE
Build endpoints to filter Pharmacy colleges by city and state.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#108]
### Description

**Notes**
+ The data of all the *pharmacy* colleges is stored in the  `data` folder.
+ Build two endpoints, one to filter data by city and the second to filter data by state.
+ One endpoint is `pharmacy_colleges/state={states_name}` and `pharmacy_colleges/city={cities_name}`

**Comment by jpphilips** [comment]
please assign to me

**Comment by nikhil25803** [comment]
Go ahead @jpphilips :)

**Comment by nikhil25803** [comment]
Any update @jpphilips?

**Comment by jpphilips** [comment]
Working on it. PR soon

**Comment by nikhil25803** [comment]
Okay :)
