### ISSUE TITLE
Build enpoints filter Dental colleges by city and state.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#109]
### What would you like to share?

**Notes**
+ Data of dental colleges is stored in the `data` folder.
+ Build two endpoints, that gives response as filtered data by the cities and states entered by the user.

### Additional information

+ Set the path as `/dental_colleges/city={}` and `/dental_colleges/state={}`.
+ User must be able to pass multiple city and state in the URL.

**Comment by ashutoshkrris** [comment]
I'd like to work on this issue.

**Comment by nikhil25803** [comment]
Sure @ashutoshkrris , go  ahead :)

**Comment by nikhil25803** [comment]
Any update @ashutoshkrris?

**Comment by ashutoshkrris** [comment]
I'm working on it and will make a PR by EOD today. @nikhil25803

**Comment by nikhil25803** [comment]
Great @ashutoshkrris :)
