### ISSUE TITLE
Update Readme 

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#111]
### Description

+ Update the endpoints in the `README.md`
+ Add [Nikhil Raj](https://github.com/nikhil25803) as the maintainer in the readme, for reference, you may check [this](https://github.com/Clueless-Community/web-ui-kit) one.

**Comment by AffanPathan02** [comment]
Can you assign me this work??

**Comment by nikhil25803** [comment]
Sure @AffanPathan02 , go ahead :))
