### ISSUE TITLE
Changes in filter.py, processing function is not there can i add, please assign me

### ISSUE THREAD

**Issue by Ajit619** [Clueless-Community/collegeAPI#121]
### Description

@nikhil25803  Changes in filter.py, processing function is not there can i add, please assign me
before:-
  output = []
    for i in range(len(data)):
        stateCheck = data[i]['state'].replace(" ", "").lower()
        if stateCheck == state:
            output.append(data[i])
    return output
after:-
 return processing(data, 'state', state)

**Comment by Ajit619** [comment]
@nikhil25803 please assign this task I have searched this very hardly in your code

**Comment by nikhil25803** [comment]
Sure @Ajit619 , go ahead :)

**Comment by Ajit619** [comment]
@nikhil25803 thanks bro your work is done
