### ISSUE TITLE
In collegeAPI/data/allengineeringcollege.json one College is missing

### ISSUE THREAD

**Issue by Ajit619** [Clueless-Community/collegeAPI#123]
### Description
@nikhil25803 this college is missing
Matoshri College Of Engineering & Research Centre, Eklhare, Nashik

**Comment by Ajit619** [comment]
@nikhil25803 please assign this task to me

**Comment by nikhil25803** [comment]
Hey @Ajit619 , we do not add colleges that are not listed in NIRF.

**Comment by Ajit619** [comment]
@nikhil25803 no problem brother
