### ISSUE TITLE
Add endpoint to filter colleges by city and state.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#124]
### Description

+ Build endpoints in`main.py` to filter colleges by city and state 
+ [This](https://github.com/Clueless-Community/collegeAPI/blob/main/data/allNirfColleges.json) is the data we need to filter out.
+ Go through the other filter endpoint and build this one accordingly.

**Comment by jpphilips** [comment]
Please assign to me

**Comment by nikhil25803** [comment]
Sure @jpphilips :)

**Comment by NeerajGartia21** [comment]
I wan to work on this issue. Can you please assign it to me.

**Comment by nikhil25803** [comment]
Hey @NeerajGartia21, it has already been assigned to someone.

**Comment by nikhil25803** [comment]
Hey @jpphilips, any update?
