### ISSUE TITLE
Build endpoint to fetch all the participated law institutes .

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#125]
### Description

**Notes**
+ [This](html) is the list of all the NIRF-ranked law colleges.
+ Build an endpoint to fetch this list
+ Set the path as `/law_colleges/nirf`

**Comment by jpphilips** [comment]
Please assign to me

**Comment by nikhil25803** [comment]
Hey @jpphilips, any updates?
