### ISSUE TITLE
Add an endpoint to fetch the overall ranked colleges by NIRF.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#126]
### Description

**Notes**
+ [This](https://www.nirfindia.org/2022/OverallRanking.html) is the list of overall colleges ranked by NIRF.
+ Build an endpoint to fetch this data.
+ Set the path as `/all/nirf`

**Comment by srini047** [comment]
Hi team, I would like to work on this issue.

**Comment by nikhil25803** [comment]
Sure @srini047, go ahead.

**Comment by nikhil25803** [comment]
Hey @srini047, any updates?

**Comment by srini047** [comment]
Hey, @nikhil25803 sorry for the inconvenience. I currently have my internals scheduled which ends tomorrow. I will update the progress tomorrow.

**Comment by srini047** [comment]
@nikhil25803 I have a small doubt.

While I was trying to add a `/all/nirf` endpoint I came to know that it already exists in the code.

https://github.com/Clueless-Community/collegeAPI/blob/main/main.py#L86-L95

Is my understanding correct? If not correct I would love to hear it.

**Comment by srini047** [comment]
Hey, @nikhil25803 shocked to see that the endpoint `/all/nirf` already exists in the `main.py` file.

**Comment by nikhil25803** [comment]
> Hey, @nikhil25803 shocked to see that the endpoint `/all/nirf` already exists in the `main.py` file.

I quotes earlier... Change that endpoint to `/all` and add your new endpoint as `/all/nirf`

**Comment by srini047** [comment]
> > Hey, @nikhil25803 shocked to see that the endpoint `/all/nirf` already exists in the `main.py` file.
> 
> I quotes earlier... Change that endpoint to `/all` and add your new endpoint as `/all/nirf`

`/all` endpoint too already exists.

**Comment by nikhil25803** [comment]
Yes, @srini047 👀
Thanks for letting me know and extremely sorry for the inconvinience.
