### ISSUE TITLE
Buid an endpoint to fetch the participated institutes overall.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#127]
### Description

**Notes**
+ [This ](https://www.nirfindia.org/2022/OverallRankingALL.html) is the list of all the participating institutes in NIRF.
+ Build an endpoint to fetch this data.
+ Set the path as `/all`

**Comment by Sourabh06** [comment]
Hi. Can I work on this?

**Comment by nikhil25803** [comment]
Sure @Sourabh06 :)
