### ISSUE TITLE
Build the endpoints to fetch all the medical colleges.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#14]
**Note** :
+ [This](https://www.nirfindia.org/2022/MedicalRankingALL.html) is the list of all the Participated Institutes Medical.
+ Set the path as `/medical_colleges/`
+ The response should return the name of the college along with the city and state.

**Comment by deathsurgeon1** [comment]
Hi @nikhil25803 , I would like to work on this

**Comment by nikhil25803** [comment]
Sure @deathsurgeon1, go ahead !!

**Comment by deathsurgeon1** [comment]
PR #17 raised and merged for above issue.
