### ISSUE TITLE
Add description to every endpoints.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#148]
### Description

**Note**
+ We need to add the description to every endpoint, describing that what this endpoint does.
+ Example : 
```python
@app.get('/all', description="All NIRF listed colleges.")
async def allNirf(page: int = 1, limit: int = 50):
    try:
        async with aiofiles.open(os.path.join(os.getcwd(), "data", "nirfAllParticipatingColleges22.json")) as file:
            output = await file.read()
    except:
        raise HTTPException(status_code=503)

    return paginate(json.loads(output), page, limit)
````
+ As you can see, after declaring the path, I added `description="  "`

**Comment by deathsurgeon1** [comment]
Hi @nikhil25803 , i would like to work on this.

**Comment by nikhil25803** [comment]
Sure @deathsurgeon1, go ahead and add description to each endpoint accordingly :)
