### ISSUE TITLE
Build the endpoint to fetch all the NIRF ranked medical colleges in India.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#15]
**Note**
+ [This](https://www.nirfindia.org/2022/MedicalRanking.html) is the list of all the medical colleges in India that are ranked by NIRF.
+ Set  the path as `/medical_colleges/nirf`
+ The response should have the name of the colleges along with their city,  state, and NIRF rankings.

**Comment by codegoggins** [comment]
Hey ! @nikhil25803 I would love to work on this , please assign it to me

**Comment by nikhil25803** [comment]
Go ahead @codegoggins !!

**Comment by nikhil25803** [comment]
Any update @codegoggins ?

**Comment by prakrit55** [comment]
Hey @nikhil25803 if this hasn't been any progress I would love to check this out.

**Comment by nikhil25803** [comment]
@prakrit55  Every assignee will get at least 7 days to make a contribution. I have raised some similar issues to build new endpoints. You may check them out.

**Comment by nikhil25803** [comment]
Hey @prakrit55, would you like to work on this issue?

**Comment by Ravina-Deogadkar** [comment]
Hey I would like to work on this

**Comment by nikhil25803** [comment]
Sure @Ravina-Deogadkar, go ahead !!!
