### ISSUE TITLE
Add an endpoint to fetch all the participated law instututes.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#154]
### Description

**Notes**
+ [This](https://www.nirfindia.org/2022/LawRankingALL.html) is the the page you need to scrape
+ Add and name the endpoint as `/law_colleges` in the `main.py`
+ Save the data in the `/data` and the python script in the `/helpers` folder.

**Comment by gaut2003** [comment]
Please assign this to me @nikhil25803

**Comment by nikhil25803** [comment]
Go ahead @gaut2003 :))

**Comment by nikhil25803** [comment]
Hey @gaut2003, any update?

**Comment by atharbeginner** [comment]
@nikhil25803 Can you assign this to me ?

**Comment by nikhil25803** [comment]
Will you able to make the PR by evening? @atharbeginner

**Comment by atharbeginner** [comment]
@nikhil25803 its already done

**Comment by nikhil25803** [comment]
Go ahead and make a PR @atharbeginner

**Comment by nikhil25803** [comment]
Merged! 
@atharbeginner, we need two more endpoints. One to filter colleges by city and other by state. Will you be able to do that?

**Comment by atharbeginner** [comment]
@nikhil25803 Can you create issue for this. Hopefully I will try this by evening!

**Comment by nikhil25803** [comment]
@atharbeginner 
Start working on it, will create an issue and assign it to you.

**Comment by atharbeginner** [comment]
@nikhil25803 did the code, just create the issue so that i can create pr

**Comment by nikhil25803** [comment]
@atharbeginner | The issue has been created, add a comment there, I'll assign it to you.
