### ISSUE TITLE
Add tags to each endpoints.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#158]
### Description

**Note**
+ One needs to add tags to each endpoint as shown in the code below
```python
# Engineering Colleges
@app.get('/engineering_colleges', description='All engineering colleges', tags=['engineering_colleges'])
async def engineeringColleges(page: int = 1, limit: int = 50):
    try:
        async with aiofiles.open(os.path.join(os.getcwd(), "data", "allEngineeringColleges.json")) as file:
            output = await file.read()
    except:
        raise HTTPException(status_code=404)
    return paginate(json.loads(output), page, limit)
```

+ The tag must be according to the endpoint. Eg. `tags=['medical_colleges']` for medical colleges endpoint.
+ This will help in improving the documentation of the project and also enhance code readability.
![image](https://user-images.githubusercontent.com/93156825/198362804-0c8eee24-11d1-4e23-8613-12b727813712.png)

**Comment by zmusaddique** [comment]
Hey! @nikhil25803 !
I would like to work on this

**Comment by nikhil25803** [comment]
Sure @zmusaddique, go ahead :))

**Comment by zmusaddique** [comment]
![image](https://user-images.githubusercontent.com/84737749/198369186-c3b39956-dc36-4b27-a4b0-fb110e239e60.png)

What should be the tag for colleges section? Just colleges?

**Comment by nikhil25803** [comment]
> ![image](https://user-images.githubusercontent.com/84737749/198369186-c3b39956-dc36-4b27-a4b0-fb110e239e60.png)
> 
> What should be the tag for colleges section? Just "colleges"?

Yes xD

**Comment by zmusaddique** [comment]
Have made a PR.
