### ISSUE TITLE
Build an UI for this project.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#16]
**Notes**
+ Idea is to give this project a user interface on the root `/` path, as a landing page.
+ Create a `templates` folder and create all the UI-related files in that folder only.
+ The template folder must have an `index.html` file. 
+ Before asking to get this issue assigned to you, please explain your idea in the comments below explaining the design(you may upload an image for reference) and the tech stack you are going to use.
+ Go through the contributing guidelines and make your contribution accordingly.

**Comment by lostgirljourney** [comment]
Hi, I want to discuss this. I am a frontend developer and I can do this using React. Tho I don't know designing very well but we can look together for inspiration.

**Comment by nikhil25803** [comment]
Sure @lostgirljourney
But instead of using a framework, we are looking to build the page using HTML, CSS, and JS only (you may use Bootstrap) so that we can render it easily as a template response in FastAPI. If you are okay with this, we can step ahead and discuss the design ideas.

**Comment by lostgirljourney** [comment]
Okay, here asked for the stack, so suggested React. And sure thing, we can go ahead with simple HTML, CSS, and JS, and it will be a new experience for me as well to work with the template response of FastAPI.

**Comment by nikhil25803** [comment]
Great!
Assigning it to you and inviting you to the [idea discussion page](https://github.com/Clueless-Community/collegeAPI/discussions/18) where we can discuss the design and once it is done, you can start working on it.

Just drop a Hi there :)

**Comment by lostgirljourney** [comment]
@nikhil25803 What exactly do you want to add to the website? Can you state that? That will give me an idea to proceed.

**Comment by nikhil25803** [comment]
### The homepage will look like this
+ Left side of the navbar - CollegeAPI.
+ Right side of the navbar - Discord and GitHub link (with logo)
+ The hero section includes written `collegeAPI` powered by `Clueless Community` in camel case with a brief description of it and on the right side of the hero section you can use any relevant SVG/PNG so that it doesn't look too minimal.
+ Something similar to what is shown below.

![image](https://user-images.githubusercontent.com/93156825/193833019-2c15db1a-abde-48aa-9ba4-a225de58e7be.png)

+ As it will be a single-page website, scrolling down, we can define our available routes and can show some sample output.

![image](https://user-images.githubusercontent.com/93156825/193834796-bf116640-c347-4bf8-b4f2-c58b776abbd9.png)

-----

All of the things I mentioned are just for reference, feel free to use your creativity. 
And yes,  you can add this feature in multiple pull requests.

**Comment by lostgirljourney** [comment]
@nikhil25803 Got you. I will start over this, might take a bit of time as exams and office both gonna go simultaneously. :)

**Comment by nikhil25803** [comment]
Sure @lostgirljourney !! No hurry :)

**Comment by rahulkarda** [comment]
Hi @nikhil25803 , look at this UI that I made for my API. If you like it then I can share the template files with you for the college API. It's built using pure HTML, CSS, and JS.

Here's my API link: https://crypto-info-api.herokuapp.com/

**Comment by nikhil25803** [comment]
It's really good @rahulkarda | You can ask @lostgirljourney and can work together. 
But I want to tell you now only that, when this PR will get merged, the points will be given to her only.

**Comment by rahulkarda** [comment]
Ok. I'll talk to her.

**Comment by nikhil25803** [comment]
Glad to have contributors like you @rahulkarda bhaiya :)
You can use this [page](https://github.com/Clueless-Community/collegeAPI/discussions/18) to discuss the idea with the team.

**Comment by rahulkarda** [comment]
Cool, thanks!

**Comment by nikhil25803** [comment]
Hey @lostgirljourney  | Any update?

**Comment by lostgirljourney** [comment]
Hey @nikhil25803, I will start now. I was having exams.

**Comment by nikhil25803** [comment]
Hey @lostgirljourney, there are only a few days left in Hactoberfest'22. Any updates?

**Comment by rahulkarda** [comment]
> Hey @lostgirljourney, there are only a few days left in Hactoberfest'22. Any updates?

Assign it to me if there's no update or I can help maybe.

**Comment by nikhil25803** [comment]
Assigned it to you bhaiya :)) @rahulkarda

**Comment by rahulkarda** [comment]
> Assigned it to you bhaiya :)) @rahulkarda

Awesome! Will start working on it.
