### ISSUE TITLE
Ideas for Winter of Code ( WOC ) 2023

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#167]
### What would you like to share?

**The following features will be integrated during WOC'23**
1. Refactor the codebase, with optimization following good practices for `Python` and `FastAPI`.
2. Enabling API key authentication for endpoints.
3. Integrate rate limiting.
4. Build a Linux container image, using `Docker`
5. Improve documentation.
6. Deployment.

### Additional information

**Regarding the deployment**
We will first try to deploy this project, with a dedicated website where a user can `login`/`signup` and generate an access key to use this API. If that doesn't work, we'll deploy it on RapidAPI.

**Comment by filza2112** [comment]
Thank you for the ideas. Do we have to perform all these tasks durinh woc or can we work on any one or few of these?
