### ISSUE TITLE
Some new endpoints

### ISSUE THREAD

**Issue by Santhosh2231** [Clueless-Community/collegeAPI#19]
- Filtering colleges from particular NIRF to another NIRF ( Let's say 10 to 20 colleges)
- Ordering the state colleges by NIRF
- Filtering colleges by multiple states
- Filtering colleges by multiple cities.

Hey!! @nikhil25803 I want to work on some of the endpoints. Check the endpoints which are really useful and please assign to me.

**Comment by nikhil25803** [comment]
For now, we have the data of all the engineering colleges. So you can add the endpoint to filter colleges by multiple states (for engineering colleges as of now only). Can you do it?

**Comment by Santhosh2231** [comment]
yea sure

**Comment by nikhil25803** [comment]
Okay !! Assigning it to you.

**Comment by Santhosh2231** [comment]
@nikhil25803 Check the pull request #21

**Comment by nikhil25803** [comment]
Great! Closing this issue.
