### ISSUE TITLE
Endpoint to fetch the list of all management colleges in India.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#23]
**Note**
+ [This](https://www.nirfindia.org/2022/ManagementRankingALL.html) is the list of all the management colleges listed in NIRF.
+ Build an endpoint that returns the name of the colleges along with their city and state.
+ Set the path as `/management_colleges`

**Comment by ighoshsubho** [comment]
*I would like to work on this*

**Comment by nikhil25803** [comment]
Sure @ighoshsubho , go ahead!

**Comment by Roshaen** [comment]
Hey @ighoshsubho share your progress

**Comment by SatabrataPaul-GitAc** [comment]
Hi @nikhil25803 
Can you assign this issue to me
Will take it up

**Comment by ighoshsubho** [comment]
*I did complete the issue with the endpoint to fetch nirf management colleges*
