### ISSUE TITLE
Build an endpoint to fetch the list of NIRF ranked management colleges. 

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#24]
**Note**
+ You have to list all the management colleges in India that are ranked by NIRF
+ You can find the list of colleges on NIRF [official website](https://www.nirfindia.org/Home)
+ Set the path as `management_colleges/nirf`
+ The output should have the name of all the colleges along with their rank, city and state.

**Comment by ighoshsubho** [comment]
**I would like to work on this**

**Comment by nikhil25803** [comment]
Okay @ighoshsubho , assigning it to you.

**Comment by nikhil25803** [comment]
Closing this issue as it is solved. Pull request #31
