### ISSUE TITLE
Design a favicon for this project.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#35]
Design a favicon(logo) that will be associated with this webpage.

**Comment by Anshika-sona** [comment]
hi, will love to work on this ,please assign me this.

**Comment by nikhil25803** [comment]
Sure @Anshika-sona | Go agead :)
Once it is done, share the link here so that other teammates can also review it.

**Comment by rohannsrivastav** [comment]
Can I also work on this?
