### ISSUE TITLE
Endpoint to fetch list Universities.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#36]
**Notes**
+ [This](https://www.nirfindia.org/2022/UniversityRanking.html) is the list of university data.
+ Scrape this data, store it in `collegeAPI/data` folder.
+ Define an endpoint to fetch the data, set the path as `/universities`
+ The response should have the names of the universities along with their city, state, and rank.

**Comment by nikhil25803** [comment]
Sure @SainathPoojary | Go ahead.

**Comment by SainathPoojary** [comment]
Hey @nikhil25803, I have raised a PR. let me know if you need any changes.

**Comment by nikhil25803** [comment]
Yes @SainathPoojary, there are some merge conflicts. Please look into this
