### ISSUE TITLE
Endpoint to fetch the details of all the colleges listed in NIRF

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#37]
**Notes**
+ [This](https://www.nirfindia.org/2022/CollegeRankingALL.html) is the list of all the participating colleges.
+ Scrape this data and store the data in the `collegeAPI/data` folder in JSON format and the scraper file in the `collegeAPI/helpers` folder.
+ Define an endpoint to fetch the list of the colleges and set the path as `/colleges`.
+ The response must have the name of the colleges along with the name of cities and state.

**Comment by ashutoshkrris** [comment]
Hi @nikhil25803 
I'd like to work on this issue.

**Comment by nikhil25803** [comment]
Sure @ashutoshkrris  | Go ahead
