### ISSUE TITLE
Endpoint to fetch the list of colleges RANKED by  NIRF.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#38]
**Notes**
+ [This](https://www.nirfindia.org/2022/CollegeRanking.html) is the list of colleges ranked by NIRF.
+ Scrape the data, store it in the `/data` folder and upload the scrapper file too in the `/helpers` folders.
+ Define an endpoint to fetch the list and set the path as `/colleges/nirf`.
+ Please note that the rank is provided for the first 100 colleges only, you need to update the rank by yourself accordingly for the colleges in the rank band 101-200.

**Comment by jpphilips** [comment]
Hello, I would like to work on this issue.

**Comment by nikhil25803** [comment]
Sure @jpphilips | Go ahead :)

**Comment by jpphilips** [comment]
Colleges from 101-200 don't have a score and are listed alphabetically. I'll rank them as they are listed, yh?

**Comment by nikhil25803** [comment]
PR has already been merged. So closing this one.
