### ISSUE TITLE
Update the new endpoints in the README.md

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#41]

**Comment by kiran-thilak** [comment]
can I work on this issue?

**Comment by nikhil25803** [comment]
Sure @kiran-thilak | Go ahead :)

**Comment by kiran-thilak** [comment]
Hi @nikhil25803, 
![image](https://user-images.githubusercontent.com/8852764/194369222-e9d57089-c3ea-4814-a993-df752641940c.png)
Please review the changes.
