### ISSUE TITLE
Enpoint to fecth NIRF ranked research institutions.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#48]
**Notes**
+ [This](https://www.nirfindia.org/2022/Ranking.html) is the data of research institutions.
+ Scrape this data and store it in `data` folder and the corresponding python file in `helpers` folder.
+ Set the endpoint as `/research_institutes`

**Comment by aniketh-varma** [comment]
Hi, I would like to work on this issue.

**Comment by nikhil25803** [comment]
Sure @aniketh-varma  | Go ahead.
