### ISSUE TITLE
Build the endpoint to fetch all  the participating pharmacy college in India.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#49]
**NOTES**
+ Scrape the data from [this](https://www.nirfindia.org/2022/PharmacyRankingALL.html) page.
+ Set the endpoint as `/pharmacy_colleges`

**Comment by jpphilips** [comment]
hello. I would like to work on this

**Comment by SatabrataPaul-GitAc** [comment]
Would like to work on this
Kindly assign it to me

**Comment by nikhil25803** [comment]
PR corresponding to this issue has already been merged. So closing this issue.
