### ISSUE TITLE
An endpoint to fetch all the NIRF ranked Pharmacy college.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#50]
**NOTES**
+ [This](https://www.nirfindia.org/2022/PharmacyRanking.html) is the list of all the pharmacy colleges that are ranked by NIRF.
+ Scrape this data and set the endpoint as `/pharmacy_colleges/nirf`

**Comment by gaut2003** [comment]
Please assign this to me.

**Comment by gaut2003** [comment]
Please assign this to me

**Comment by nikhil25803** [comment]
Sure @gaut2003 | Go ahead.
