### ISSUE TITLE
Build an endpoint to fetch all the NIRF ranked Dental college.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#54]
**Notes**
+ [This](https://www.nirfindia.org/2022/DentalRanking.html) is the list of all the dental colleges ranked by NIRF.
+ Store the scrapped data in `data` folder in JSON format and the scrapper in the `helpers` folder.
+ Define the endpoint as `/dental_colleges/nirf`
+ The response should have the names of the colleges along with their rank, city, and state.

**Comment by SatabrataPaul-GitAc** [comment]
Assign this issue to me 
Would like to work on this

**Comment by nikhil25803** [comment]
Closing this, as the corresponding PR has already been merged.
