### ISSUE TITLE
Some college seems to be missing

### ISSUE THREAD

**Issue by sayakongit** [Clueless-Community/collegeAPI#56]
I found that some engineering colleges of my city are missing in the list.

**Comment by nikhil25803** [comment]
Add them and make a PR @sayakongit

**Comment by M-Rahul1** [comment]
Can I too add colleges in my area @nikhil25803

**Comment by nikhil25803** [comment]
No @M-Rahul1 | These are nirf-listed colleges. So it will anyhow get refreshed when the code will run again.
