### ISSUE TITLE
Endpoint to fetch the details of all the participated dental institutes.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#57]
**Notes**
+ [This](https://www.nirfindia.org/2022/DentalRankingALL.html) is the list of all the participated dental colleges.
+ Store the scrapped data in `data` folder in JSON format and the scrapper in the `helpers` folder.
+ Define the endpoint as `/dental_colleges`
+ The response should have the names of the colleges along with their city, and state.

**Comment by SatabrataPaul-GitAc** [comment]
Assign this issue to me 
Would like to contribute to this

**Comment by gaut2003** [comment]
Please assign this to me.

**Comment by gaut2003** [comment]
Hey @nikhil25803 I have made the required changes and sent you a PR related to it. Kindly check.

**Comment by SatabrataPaul-GitAc** [comment]
Should I raise my PR @nikhil25803 
I was assigned this 
So was working on it

**Comment by nikhil25803** [comment]
Sure @SatabrataPaul-GitAc bhaiya :)
