### ISSUE TITLE
Endpoint to fetch all the law colleges ranked by NIRF.

### ISSUE THREAD

**Issue by nikhil25803** [Clueless-Community/collegeAPI#58]
+ [This](https://www.nirfindia.org/2022/LawRanking.html) is the list of all the law college ranked by NIRF.
+ Store the scrapped data in `data` folder in JSON format and the scrapper in the `helpers` folder.
+ Define the endpoint as `/law_colleges/nirf`
+ The response should have the names of the colleges along with their rank, city, and state.

**Comment by SatabrataPaul-GitAc** [comment]
Want to work on this
Kindly assign it to me
