### ISSUE TITLE
Endpoint to fetch all the Architecture colleges ranked by NIRF.

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/collegeAPI#67]
## I would like to work on this :
1. I will fetch the list of all the Architecture college ranked by NIRF.
2. Store the scrapped data in data folder in JSON format and the scrapper in the helpers folder.
3. Define the endpoint as /architecture_colleges/nirf
4. I will make the response such that it should have the names of the colleges along with their rank, city, and state.

**Comment by nikhil25803** [comment]
Sure @ighoshsubho  |  Go ahead :)
