### ISSUE TITLE
Redundant raise error was present

### ISSUE THREAD

**Issue by OMH-G** [Clueless-Community/collegeAPI#68]
**Description**
Redundant raise error was present at medical `/medical_colleges/city={city}` endpoint I have made some changes and removed extra raise present in api endpoint to reduce line of code can you go through it @nikhil25803 ?

Link :https://github.com/Clueless-Community/collegeAPI/pull/65#issue-1401960451

**Comment by nikhil25803** [comment]
Closing this issue as the PR has been merged :)
