### ISSUE TITLE
Endpoint to fetch the details of all the participated architecture colleges.

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/collegeAPI#69]
## I want to work on this :
1. I would like to add the list of all the participated architecture colleges.
2. Store the scrapped data in data folder in JSON format and the scrapper in the helpers folder.
3. Define the endpoint as /architecture_colleges
4. I will make sure that the response should have the names of the colleges along with their city, and state.

**Comment by nikhil25803** [comment]
Sure @ighoshsubho  | Go ahead :))
