### ISSUE TITLE
Endpoint to fetch the details of research colleges

### ISSUE THREAD

**Issue by prakrit55** [Clueless-Community/collegeAPI#72]
- [This](https://www.nirfindia.org/2022/ResearchRanking.html) is the list of all the research colleges.
- Store the scrapped data in data folder in JSON format and the scrapper in the helpers folder.
- Define the endpoint as /research_colleges
- The response should have the names of the colleges along with their rank, city, and state.

**Comment by prakrit55** [comment]
If this is reviewed and accepted , please do assign me.

**Comment by nikhil25803** [comment]
Go ahead @prakrit55 |

**Comment by nikhil25803** [comment]
Closing this one as the corresponding PR has already been merged.
