### ISSUE TITLE
Endpoint to fetch the details of all Research colleges ranked by NIRF.

### ISSUE THREAD

**Issue by prakrit55** [Clueless-Community/collegeAPI#73]
- [This](https://www.nirfindia.org/2022/ResearchRanking.html) is the list of all the research colleges ranked by nirf.
- Store the scrapped data in data folder in JSON format and the scrapper in the helpers folder.
- Define the endpoint as /research_colleges/nirf
- The response should have the names of the colleges along with their rank, city, and state.

**Comment by prakrit55** [comment]
I would like to work on this if it is accepted.

**Comment by nikhil25803** [comment]
Sure @prakrit55  | Go ahead

**Comment by nikhil25803** [comment]
Closing this one as the corresponding PR has already been merged. Thanks @prakrit55  :D
