### ISSUE TITLE
Function concept need to implement to reduce line of code and improve optimization in filters.py

### ISSUE THREAD

**Issue by OMH-G** [Clueless-Community/collegeAPI#85]
I have made some changes in **filters.py** that is added one processing function to manipulate the task and its line of code is reduced
can you have a look through it @nikhil25803 
link : https://github.com/Clueless-Community/collegeAPI/pull/84#issue-1402255059

**Comment by nikhil25803** [comment]
Closing this issue as the corresponding PR has already been merged.
