### ISSUE TITLE
feat: Add pull request template and issue templates 

### ISSUE THREAD

**Issue by shashankbhatgs** [Clueless-Community/collegeAPI#89]
## Description 
There are currently no issue templates and the pull request template. I would like to add these so that it'll help folks contributing to the project by giving a structured way to describe the problem.

**Comment by shashankbhatgs** [comment]
Also, to cover every detail can I use the same templates from the main page, clueless-official-website? @nikhil25803  @Roshaen

**Comment by Roshaen** [comment]
> Also, to cover every detail can I use the same templates from the main page, clueless-official-website? @nikhil25803 @Roshaen

Yes, you can
Go for it
