### ISSUE TITLE
Optimization needed and response need to return 1D list instead of 2D list

### ISSUE THREAD

**Issue by OMH-G** [Clueless-Community/collegeAPI#97]
### Before 

In the response I have checked that it was returning 2D response and main.py there were some lines in api which were repeated again function is needed.
### After 
Using **extend** keyword instead of **append** keyword inside the api like `engineering_colleges/state={state}` worked and it returned 1D array as it will be better for further processing and extraction .
can you have a closer look @nikhil25803 ?

### Before 
![Screenshot (216)](https://user-images.githubusercontent.com/70062727/194864466-1bf8f3fb-3659-43d9-a7e8-f1bd75bfe176.png)
### After 
![Screenshot (217)](https://user-images.githubusercontent.com/70062727/194865891-ef3a8d03-756f-40e0-9a13-4210b8675d12.png)

Also main.py LOC is reduced by adding function `colleges_by_state_or_city` and passing useful variables for further understanding

**Comment by nikhil25803** [comment]
Closing this one, thanks for contributing :)
